#!/bin/bash

echo "🔧 Questo script spiega come risolvere il problema auto-update Windows"
echo ""
echo "PROBLEMA IDENTIFICATO:"
echo "  - I file .exe hanno nomi con punti invece di spazi"
echo "  - Il file latest.yml potrebbe essere incompleto/corrotto"
echo ""
echo "SOLUZIONE:"
echo "  1. Vai su: https://github.com/g-momo5/CO-OP/actions"
echo "  2. Click su 'Build Windows'"
echo "  3. Click 'Run workflow' → Run workflow"
echo "  4. Attendi completamento (~10 min)"
echo "  5. Scarica l'artifact 'windows-build-XXX'"
echo "  6. Estrai lo ZIP - troverai:"
echo "     - CO-OP Setup 1.0.11.exe  (con SPAZI)"
echo "     - CO-OP 1.0.11.exe  (con SPAZI)"
echo "     - latest.yml  (formato corretto)"
echo "  7. Carica QUESTI file (con spazi) nella release"
echo ""
echo "IMPORTANTE:"
echo "  - electron-updater cerca file con SPAZI nel nome"
echo "  - latest.yml deve essere generato da electron-builder"
echo "  - NON rinominare manualmente i file"
echo ""
