[[redirects]]
  from = "/m"
  to = "/mobile/index.html"
  status = 200

[[redirects]]
  from = "/m/"
  to = "/mobile/index.html"
  status = 200

[[redirects]]
  from = "/m/*"
  to = "/mobile/index.html"
  status = 200

[[redirects]]
  from = "/mobile"
  to = "/mobile/index.html"
  status = 200

[[redirects]]
  from = "/mobile/"
  to = "/mobile/index.html"
  status = 200

[[headers]]
  for = "/.netlify/functions/mobile-data"
  [headers.values]
    Cache-Control = "no-store"
