[[redirects]]
  from = "/m"
  to = "/mobile/index.html"
  status = 200

[[redirects]]
  from = "/m/"
  to = "/mobile/index.html"
  status = 200

[[redirects]]
  from = "/m/*"
  to = "/mobile/index.html"
  status = 200

[[redirects]]
  from = "/mobile"
  to = "/mobile/index.html"
  status = 200

[[redirects]]
  from = "/mobile/"
  to = "/mobile/index.html"
  status = 200

[[headers]]
  for = "/.netlify/functions/mobile-data"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"

[[headers]]
  for = "/m"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"

[[headers]]
  for = "/m/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"

[[headers]]
  for = "/mobile"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"

[[headers]]
  for = "/mobile/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"

[[headers]]
  for = "/mobile-assets/*"
  [headers.values]
    Cache-Control = "no-cache, max-age=0"
